STATUS_MAPPING = {
    "not_started": "Not Started",
    "started": "Started",
    "prepared": "Prepared",
    "mailed": "Mailed",
    "not_delivered": "Not Delivered",
    "delivered": "Delivered",
    "returned_signed": "Returned Signed",
    "returned_not_signed": "Not Returned",
    "attorney_submit": "Handed over case to Attorney",
    "direct_submit": "Applied For Surplus",
    "motion_granted": "Application Granted",
    "motion_denied": "Application Denied",
    "not_assigned": "Not Assigned",
    "assigned": "Assigned",
    "completed": "Completed",
    "verified": "Verified",
    "pending": "Pending",
    "skiptraced_found": "Skiptraced Found",
    "skiptraced_not_found": "Skiptraced Not Found",
    "cold_calling_located": "Cold Calling Located",
    "cold_calling_not_located": "Cold Calling Not Located",
    "need_to_call": "Need to Call",
    "responded": "Responded",
    "not_responded": "Not Responded",
    "re_skiptrace": "Re-Skiptrace",
    "interested": "Interested",
    "not_interested": "Not Interested",
    "not_sure": "Not Sure",
    "preparing_documents": "Preparing Documents",
    "agreement_sent": "Agreement Sent",
    "conversion_in_progress": "Conversion In Progress",
    "closed_funded": "Closed Funded",
    "closed_not_funded": "Closed Not Funded",
    "": "",
}
