# Generated by Django 4.2.17 on 2025-03-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_directory', '0003_foreclosure_events_assigned_to_and_more'),
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='state',
            field=models.ManyToManyField(related_name='selected_states', to='realestate_directory.foreclosure_events'),
        ),
    ]
