# Generated by Django 4.2.17 on 2025-06-11 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0042_status_negotiation_status_alter_status_call_status'),
        ('Client', '0003_rename_usersettings_clientsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('f_note', models.CharField(blank=True, max_length=255, null=True)),
                ('f_result', models.CharField(blank=True, max_length=255, null=True)),
                ('f_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=255)),
                ('leads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_as_lead', to='propertydata.status')),
            ],
        ),
    ]
