# Generated by Django 4.2.17 on 2025-06-13 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Client', '0004_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='client_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followup',
            name='f_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=255),
        ),
    ]
