# Generated by Django 4.2.17 on 2025-06-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0005_followup_client_name_alter_followup_f_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followup',
            old_name='client_name',
            new_name='client',
        ),
    ]
