# Generated by Django 4.2.17 on 2025-01-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0002_email_landline_number_property_wireless_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=255, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last Name')),
                ('name_suffix', models.CharField(blank=True, max_length=255, verbose_name='Suffix')),
                ('emails', models.ManyToManyField(blank=True, related_name='contact_as_email', to='si_user.email', verbose_name='Email Addresses')),
                ('landline', models.ManyToManyField(blank=True, related_name='contact_as_landline', to='si_user.landline_number', verbose_name='Landline Numbers')),
                ('mailing_address', models.ManyToManyField(blank=True, related_name='contacts_as_mailing_address', to='si_user.property', verbose_name='Mailing Address')),
                ('wireless', models.ManyToManyField(blank=True, related_name='contact_as_wireless', to='si_user.wireless_number', verbose_name='Wireless Numbers')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
