# Generated by Django 4.2.17 on 2025-01-10 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('deed', 'Deed'), ('loan', 'Loan'), ('lien', 'Lien'), ('release', 'Release')], default='Transaction Type', max_length=255, verbose_name='Transaction Type')),
                ('instrument_no', models.CharField(blank=True, max_length=255, verbose_name='Instrument No')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, verbose_name='Transaction Amount')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Comment')),
                ('reference_transaction', models.CharField(blank=True, max_length=255, verbose_name='Reference Transaction')),
                ('first_party', models.ManyToManyField(blank=True, related_name='transactions_as_first_party', to='si_user.contact', verbose_name='First Party - Grantor, Seller, Borrower)')),
                ('property', models.ManyToManyField(related_name='transactions_as_property', to='si_user.property', verbose_name='Property')),
                ('second_party', models.ManyToManyField(blank=True, related_name='transactions_as_second_party', to='si_user.contact', verbose_name='Second Party - Grantee, Buyer, Lender')),
                ('third_party', models.ManyToManyField(blank=True, related_name='transactions_as_third_party', to='si_user.contact', verbose_name='Third Party - Trustee, Guarantor, Attorney')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Court_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('case_number', models.CharField(blank=True, max_length=255, verbose_name='Case Number')),
                ('court_name', models.CharField(blank=True, max_length=255, verbose_name='Court Name')),
                ('case_type', models.CharField(blank=True, max_length=255, verbose_name='Case Type')),
                ('case_status', models.CharField(blank=True, max_length=255, verbose_name='Case Status')),
                ('defendant', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='court_records_as_defendant', to='si_user.contact', verbose_name='Defendant')),
                ('plaintiff', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='court_records_as_plaintiff', to='si_user.contact', verbose_name='Plaintiff')),
                ('property', models.ManyToManyField(blank=True, related_name='court_records', to='si_user.property', verbose_name='Property')),
            ],
            options={
                'verbose_name': 'Court Record',
                'verbose_name_plural': 'Court Records',
            },
        ),
    ]
