# Generated by Django 4.2.17 on 2025-01-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0004_transaction_court_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, verbose_name='Transaction Amount'),
        ),
    ]
