# Generated by Django 4.2.17 on 2025-01-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0005_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='zip_code',
            field=models.IntegerField(blank=True, default='00000', verbose_name='Zip'),
        ),
    ]
