# Generated by Django 4.2.17 on 2025-01-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0006_alter_property_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='zip_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Zip'),
        ),
    ]
