# Generated by Django 4.2.17 on 2025-01-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0008_remove_court_record_defendant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='foreclosure',
        ),
    ]
