# Generated by Django 4.2.17 on 2025-01-30 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('si_user', '0009_delete_foreclosure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='purchased_credit_balance',
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('free_credit_balance', models.IntegerField(default=20)),
                ('purchased_credit_balance', models.IntegerField(default=0)),
                ('Total_credits', models.IntegerField(default=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
