# Generated by Django 4.2.17 on 2025-02-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0011_alter_userdetail_total_credits_alter_userdetail_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
