# Generated by Django 4.2.17 on 2025-03-04 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0014_userdetail_stripe_customer_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subscription',
        ),
    ]
