# Generated by Django 4.2.17 on 2025-04-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0015_delete_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='user_type',
            field=models.CharField(blank=True, choices=[('si_client', 'SI Client'), ('manual_client', 'Manual Client')], default='SI Client', max_length=100, null=True),
        ),
    ]
