# Generated by Django 4.2.17 on 2025-04-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Client', '0001_initial'),
        ('si_user', '0016_userdetail_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, to='Admin_Client.orders'),
        ),
    ]
