# Generated by Django 4.2.17 on 2025-04-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Client', '0002_remove_deliveries_order_orders_deliveries'),
        ('si_user', '0017_userdetail_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='orders',
            field=models.ManyToManyField(blank=True, to='Admin_Client.orders'),
        ),
    ]
