# Generated by Django 4.2.17 on 2025-04-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0020_userdetail_changed_at_userdetail_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
