# Generated by Django 4.2.17 on 2025-04-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0032_alter_contact_changed_at_and_more'),
        ('si_user', '0022_creditusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditusage',
            name='leads',
            field=models.ManyToManyField(blank=True, to='propertydata.status'),
        ),
    ]
