# Generated by Django 4.2.17 on 2025-04-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0024_alter_creditusage_credits_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='phone',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
