# Generated by Django 4.2.17 on 2025-05-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0026_alter_userdetail_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditusage',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='creditusage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user_type',
            field=models.CharField(blank=True, choices=[('si_client', 'SI Client'), ('manual_client', 'Manual Client')], default='si_client', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
    ]
