# Generated by Django 4.2.17 on 2025-08-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0028_subscriptionplan_stripesubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='type',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('payperlead', 'Pay Per Lead')], max_length=20, null=True),
        ),
    ]
