# Generated by Django 4.2.17 on 2025-08-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0029_subscriptionplan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='interval',
            field=models.CharField(choices=[('month', 'Monthly'), ('half_yearly', 'Half Yearly'), ('year', 'Yearly')], max_length=20),
        ),
    ]
