# Generated by Django 4.2.17 on 2025-08-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0031_subscriptionplan_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='brochure',
            field=models.URLField(blank=True, null=True),
        ),
    ]
