# Generated by Django 4.2.17 on 2025-08-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0032_subscriptionplan_brochure'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('failed', 'Failed'), ('past_due', 'Past Due'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='transaction_source',
            field=models.CharField(blank=True, choices=[('subscription', 'Subscription'), ('payg', 'Pay As You Go')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='currency',
            field=models.CharField(default='usd', max_length=10),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='number_of_leads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
