# Generated by Django 4.2.17 on 2025-08-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0034_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
