# Generated by Django 4.2.17 on 2025-08-15 09:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Admin_Client', '0007_alter_orders_transaction'),
        ('si_user', '0035_transactions_stripe_invoice_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='UserTransactions',
        ),
    ]
