# Generated by Django 4.2.17 on 2025-08-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0036_rename_transactions_usertransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripesubscription',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
