# Generated by Django 4.2.17 on 2025-09-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0037_stripesubscription_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('changed_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('effective_date', models.DateField()),
                ('detail', models.CharField(blank=True, max_length=255, null=True)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
