# Generated by Django 4.2.17 on 2025-09-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0038_announcements'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='lead_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
