# Generated by Django 4.2.17 on 2025-11-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0039_subscriptionplan_lead_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='activation_attempt',
            field=models.IntegerField(default=0),
        ),
    ]
