# Generated by Django 4.2.17 on 2025-11-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0040_userdetail_activation_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='activation_attempt',
            field=models.IntegerField(default=1),
        ),
    ]
