# Generated by Django 4.2.17 on 2026-02-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0041_alter_userdetail_activation_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='payment_method',
            field=models.CharField(choices=[('not added', 'Not Added'), ('added', 'Added'), ('expired', 'Expired'), ('not working', 'Not Working')], default='not added', max_length=100, null=True),
        ),
    ]
