# Generated by Django 4.2.17 on 2026-02-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0042_userdetail_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('sale_type', models.CharField(blank=True, max_length=100, null=True)),
                ('surplus_type', models.CharField(blank=True, max_length=100, null=True)),
                ('price_id', models.CharField(max_length=255)),
                ('stripe_product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('interval', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
