# Generated by Django 4.2.17 on 2026-02-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0043_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plans',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plans',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
