# Generated by Django 4.2.17 on 2026-02-26 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0044_plans_long_description_plans_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripesubscription',
            name='plan',
        ),
        migrations.AddField(
            model_name='stripesubscription',
            name='plans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='si_user.plans'),
        ),
    ]
