# Generated by Django 4.2.17 on 2026-02-26 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0045_remove_stripesubscription_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripesubscription',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='si_user.subscriptionplan'),
        ),
    ]
