# Generated by Django 4.2.17 on 2026-03-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0064_alter_foreclosure_sale_status'),
        ('si_user', '0046_stripesubscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='post_foreclosure_delivered',
            field=models.ManyToManyField(related_name='post_f_delivered', to='propertydata.foreclosure'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='pre_foreclosure_delivered',
            field=models.ManyToManyField(related_name='pre_f_delivered', to='propertydata.foreclosure'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='verified_surplus_delivered',
            field=models.ManyToManyField(related_name='verified_s_delivered', to='propertydata.foreclosure'),
        ),
    ]
