# Generated by Django 4.2.17 on 2025-08-19 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0002_projects_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='status',
            new_name='active',
        ),
    ]
