# Generated by Django 4.2.17 on 2025-08-21 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProjectManager', '0003_rename_status_projects_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('changed_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('year', models.CharField(max_length=100)),
                ('week', models.IntegerField()),
                ('cycle_start', models.DateField()),
                ('cycle_end', models.DateField()),
                ('sale_from', models.DateField()),
                ('sale_to', models.DateField()),
                ('completed', models.DateField()),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('active', 'Active'), ('running', 'Running'), ('completed', 'Completed'), ('closed', 'Closed')], max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.projects')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TasksTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('changed_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('weekday', models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=255)),
                ('task_group', models.CharField(blank=True, max_length=255, null=True)),
                ('task_name', models.CharField(blank=True, max_length=255, null=True)),
                ('job_detail', models.TextField()),
                ('archived', models.BooleanField(default=False)),
                ('assigned_to', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.projects')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('changed_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('task_name', models.CharField(blank=True, max_length=255, null=True)),
                ('task_group', models.CharField(choices=[('datask', 'Data Entry'), ('admintask', 'Admin Task')], max_length=255)),
                ('date_assigned', models.DateField()),
                ('delivery_date', models.DateField()),
                ('reporting_date', models.DateField()),
                ('description', models.TextField()),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('delivered', 'Delivered'), ('completed', 'Completed')], max_length=255)),
                ('assigned_to', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.updatecycle')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.projects')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
