# Generated by Django 4.2.17 on 2025-08-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0004_updatecycle_taskstemplate_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatecycle',
            name='completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
