# Generated by Django 4.2.17 on 2025-08-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0006_alter_tasks_assigned_to_alter_tasks_cycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstemplate',
            name='task_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
