# Generated by Django 4.2.17 on 2025-08-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0007_taskstemplate_task_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstemplate',
            name='task_duration',
            field=models.IntegerField(blank=True, default=3),
            preserve_default=False,
        ),
    ]
