# Generated by Django 4.2.17 on 2025-08-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0008_alter_taskstemplate_task_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstemplate',
            name='job_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
