# Generated by Django 4.2.17 on 2025-08-23 07:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProjectManager', '0009_alter_taskstemplate_job_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstemplate',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
