# Generated by Django 4.2.17 on 2025-08-23 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0011_alter_tasks_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ProjectManager.taskstemplate'),
        ),
        migrations.AlterField(
            model_name='taskstemplate',
            name='task_group',
            field=models.CharField(blank=True, choices=[('datask', 'Data Entry'), ('admintask', 'Admin Task')], max_length=255, null=True),
        ),
    ]
