# Generated by Django 4.2.17 on 2025-08-27 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0012_tasks_template_alter_taskstemplate_task_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('changed_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('viewname', models.CharField(blank=True, max_length=255)),
                ('taskname', models.CharField(blank=True, max_length=255)),
                ('weekday', models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=255)),
                ('duration', models.IntegerField(blank=True)),
                ('group', models.CharField(blank=True, choices=[('datask', 'Data Entry'), ('admintask', 'Admin Task')], max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('delivered', 'Delivered'), ('completed', 'Completed')], default='created', max_length=255),
        ),
        migrations.AddField(
            model_name='taskstemplate',
            name='taskview',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.taskviews'),
        ),
    ]
