# Generated by Django 4.2.17 on 2025-08-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0013_taskviews_alter_tasks_status_taskstemplate_taskview'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatecycle',
            name='pf_list',
            field=models.URLField(blank=True, null=True),
        ),
    ]
