# Generated by Django 4.2.17 on 2025-08-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0015_tasks_time_captured_timetracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='tracker_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('started', 'Started'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='idle', max_length=255),
        ),
    ]
