# Generated by Django 4.2.17 on 2025-08-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0016_tasks_tracker_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='case_searched',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='contact_volume',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='lead_volume',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='published',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='skiptraced',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
