# Generated by Django 4.2.17 on 2025-08-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0018_tasks_post_foreclosure_case_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='post_foreclosure_case_searched',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
