# Generated by Django 4.2.17 on 2025-08-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0019_tasks_post_foreclosure_case_searched'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='post_foreclosure_update_interval',
            field=models.IntegerField(default=7),
        ),
    ]
