# Generated by Django 4.2.17 on 2025-08-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0052_alter_status_call_status_and_more'),
        ('ProjectManager', '0020_projects_post_foreclosure_update_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='post_foreclosure_cases',
            field=models.ManyToManyField(blank=True, null=True, to='propertydata.foreclosure'),
        ),
    ]
