# Generated by Django 4.2.17 on 2025-09-03 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0039_subscriptionplan_lead_number'),
        ('ProjectManager', '0021_tasks_post_foreclosure_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='si_user.stripesubscription'),
        ),
        migrations.AddField(
            model_name='projects',
            name='sale_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
