# Generated by Django 4.2.17 on 2025-09-03 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0039_subscriptionplan_lead_number'),
        ('ProjectManager', '0022_projects_plan_projects_sale_type_projects_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='si_user.subscriptionplan'),
        ),
    ]
