# Generated by Django 4.2.17 on 2025-09-05 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0054_alter_foreclosure_sale_status'),
        ('si_user', '0039_subscriptionplan_lead_number'),
        ('ProjectManager', '0023_alter_projects_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='active_subscribers',
            field=models.ManyToManyField(to='si_user.stripesubscription'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='post_foreclosure_cases',
            field=models.ManyToManyField(to='propertydata.foreclosure'),
        ),
        migrations.CreateModel(
            name='DeliveryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('changed_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('delivered', models.IntegerField(default=0)),
                ('report', models.CharField(blank=True, max_length=255, null=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectManager.tasks')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
