# Generated by Django 4.2.17 on 2025-09-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0054_alter_foreclosure_sale_status'),
        ('si_user', '0039_subscriptionplan_lead_number'),
        ('ProjectManager', '0025_deliveryreport_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='active_subscribers',
            field=models.ManyToManyField(blank=True, null=True, to='si_user.stripesubscription'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='date_assigned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='post_foreclosure_cases',
            field=models.ManyToManyField(blank=True, null=True, to='propertydata.foreclosure'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='reporting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
