# Generated by Django 4.2.17 on 2025-09-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0039_subscriptionplan_lead_number'),
        ('propertydata', '0054_alter_foreclosure_sale_status'),
        ('ProjectManager', '0026_alter_tasks_active_subscribers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='active_subscribers',
            field=models.ManyToManyField(blank=True, to='si_user.stripesubscription'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='post_foreclosure_cases',
            field=models.ManyToManyField(blank=True, to='propertydata.foreclosure'),
        ),
    ]
