# Generated by Django 4.2.17 on 2026-01-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0063_status_changed_at_status_created_at'),
        ('ProjectManager', '0028_projectissues'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('changed_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('state', models.CharField(max_length=225, null=True)),
                ('county', models.CharField(max_length=225, null=True)),
                ('case_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Case Number')),
                ('case_number_ext', models.CharField(blank=True, default='', max_length=10, verbose_name='Case Extension')),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('sale_type', models.CharField(blank=True, choices=[('tax', 'Tax'), ('mortgage', 'Mortgage')], max_length=225, null=True)),
                ('appraised_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fcl_final_judgment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('possible_surplus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('verified_surplus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale_status', models.CharField(blank=True, choices=[('pending', 'Active'), ('sold', 'Sold'), ('unsold', 'Unsold'), ('cancelled', 'Cancelled'), ('sold_to_plaintiff', 'Sold To Plaintiff'), ('bankruptcy_hold', 'Bankruptcy Hold')], max_length=225, null=True)),
                ('surplus_status', models.CharField(blank=True, choices=[('not determined', 'Not Determined'), ('possible surplus', 'Possible Surplus'), ('no possible surplus', 'No Possible Surplus'), ('fund available', 'Fund Available'), ('motion filed', 'Motion Filed'), ('fund claimed', 'Fund Claimed'), ('no surplus', 'No Surplus')], default='Not Determined', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('auction_source', models.CharField(blank=True, max_length=255, null=True)),
                ('parcel', models.CharField(blank=True, max_length=255, verbose_name='Parcel ID')),
                ('house_number', models.CharField(blank=True, max_length=255, verbose_name='House')),
                ('road_name', models.CharField(blank=True, max_length=255, verbose_name='Road')),
                ('road_type', models.CharField(blank=True, max_length=255, verbose_name='Road Type')),
                ('direction', models.CharField(blank=True, max_length=255, verbose_name='Direction')),
                ('apt_unit', models.CharField(blank=True, max_length=255, verbose_name='Apartment/Unit')),
                ('extention', models.CharField(blank=True, max_length=255, verbose_name='Extension')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='City')),
                ('zip_code', models.CharField(blank=True, max_length=255, verbose_name='Zip')),
                ('plaintiff', models.CharField(blank=True, max_length=255)),
                ('business_name', models.CharField(blank=True, max_length=255, verbose_name='Business Name')),
                ('designation', models.CharField(blank=True, max_length=100, verbose_name='Designation')),
                ('name_prefix', models.CharField(blank=True, max_length=10, verbose_name='Prefix')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=255, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last Name')),
                ('name_suffix', models.CharField(blank=True, max_length=10, verbose_name='Suffix')),
                ('update_status', models.CharField(blank=True, choices=[('created', 'Created'), ('updated', 'Updated')], default='created', max_length=255)),
                ('update_type', models.CharField(blank=True, choices=[('new', 'New'), ('exist', 'Exist')], max_length=255)),
                ('s_defendant', models.ManyToManyField(blank=True, to='propertydata.contact')),
                ('s_foreclosure', models.ManyToManyField(blank=True, to='propertydata.foreclosure')),
                ('s_plaintiff', models.ManyToManyField(blank=True, to='propertydata.foreclosingentity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('changed_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=255)),
                ('data', models.ManyToManyField(null=True, to='ProjectManager.temporarydata')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
