# Generated by Django 4.2.17 on 2026-01-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0029_temporarydata_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='data',
            field=models.ManyToManyField(to='ProjectManager.temporarydata'),
        ),
    ]
