# Generated by Django 4.2.17 on 2026-01-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0030_alter_upload_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarydata',
            name='case_lookup',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
