# Generated by Django 4.2.17 on 2026-01-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0063_status_changed_at_status_created_at'),
        ('ProjectManager', '0031_temporarydata_case_lookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarydata',
            name='s_property',
            field=models.ManyToManyField(blank=True, to='propertydata.property'),
        ),
    ]
