# Generated by Django 4.2.17 on 2026-01-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0063_status_changed_at_status_created_at'),
        ('ProjectManager', '0032_temporarydata_s_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarydata',
            name='u_defendant',
            field=models.ManyToManyField(blank=True, related_name='update_def', to='propertydata.contact'),
        ),
        migrations.AddField(
            model_name='temporarydata',
            name='u_foreclosure',
            field=models.ManyToManyField(blank=True, related_name='update_fcl', to='propertydata.foreclosure'),
        ),
        migrations.AddField(
            model_name='temporarydata',
            name='u_plaintiff',
            field=models.ManyToManyField(blank=True, related_name='update_plt', to='propertydata.foreclosingentity'),
        ),
        migrations.AddField(
            model_name='temporarydata',
            name='u_property',
            field=models.ManyToManyField(blank=True, related_name='update_prop', to='propertydata.property'),
        ),
        migrations.AlterField(
            model_name='temporarydata',
            name='s_defendant',
            field=models.ManyToManyField(blank=True, related_name='suggested_def', to='propertydata.contact'),
        ),
        migrations.AlterField(
            model_name='temporarydata',
            name='s_foreclosure',
            field=models.ManyToManyField(blank=True, related_name='suggested_fcl', to='propertydata.foreclosure'),
        ),
        migrations.AlterField(
            model_name='temporarydata',
            name='s_plaintiff',
            field=models.ManyToManyField(blank=True, related_name='suggested_plt', to='propertydata.foreclosingentity'),
        ),
        migrations.AlterField(
            model_name='temporarydata',
            name='s_property',
            field=models.ManyToManyField(blank=True, related_name='suggested_prop', to='propertydata.property'),
        ),
    ]
