# Generated by Django 4.2.17 on 2026-01-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0033_temporarydata_u_defendant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarydata',
            name='update_type',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('exist', 'Exist')], default='new', max_length=255),
        ),
    ]
