# Generated by Django 4.2.17 on 2025-09-18 05:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Communication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailmessage',
            name='body',
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='bcc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='body_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='body_plain',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='cc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='thread_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='uid',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='Communication.mailaccount'),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='folder',
            field=models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('archive', 'Archive'), ('important', 'Important')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='message_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='recipient',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
