# Generated by Django 4.2.17 on 2025-09-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communication', '0002_remove_mailmessage_body_mailmessage_bcc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmessage',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='uid',
            field=models.CharField(max_length=255),
        ),
    ]
