# Generated by Django 4.2.17 on 2025-09-18 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Communication', '0003_alter_mailmessage_message_id_alter_mailmessage_uid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mailmessage',
            unique_together={('account', 'message_id', 'folder')},
        ),
    ]
