# Generated by Django 4.2.17 on 2025-09-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communication', '0004_alter_mailmessage_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mailmessage',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='folder',
            field=models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('archive', 'Archive'), ('important', 'Important')], default='inbox', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='mailmessage',
            unique_together={('account', 'uid', 'folder')},
        ),
    ]
