# Generated by Django 4.2.17 on 2025-09-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communication', '0005_alter_mailmessage_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmessage',
            name='thread_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
