# Generated by Django 4.2.17 on 2025-09-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communication', '0006_mailmessage_thread_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmessage',
            name='thread_key',
            field=models.CharField(db_index=True, editable=False, max_length=64),
        ),
    ]
