# Generated by Django 4.2.17 on 2025-09-22 18:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Communication', '0007_alter_mailmessage_thread_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=17, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contacts', models.ManyToManyField(to='Communication.clientcontact')),
            ],
        ),
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('signature', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('single', 'Single Recipient'), ('multiple', 'Multiple Recipients')], max_length=10)),
                ('recipient', models.EmailField(blank=True, max_length=254, null=True)),
                ('recipients_list', models.TextField(blank=True, null=True)),
                ('custom_subject', models.CharField(blank=True, max_length=200, null=True)),
                ('custom_body', models.TextField(blank=True, null=True)),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('contact_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Communication.contactlist')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Communication.mailaccount')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Communication.mailtemplate')),
            ],
        ),
    ]
