# Generated by Django 4.2.17 on 2025-09-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communication', '0008_clientcontact_contactlist_mailtemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledemail',
            name='send_to_clients',
            field=models.BooleanField(default=False),
        ),
    ]
