# Generated by Django 4.2.17 on 2025-09-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_directory', '0009_states'),
        ('Communication', '0009_scheduledemail_send_to_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontact',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='preferred_states',
            field=models.ManyToManyField(to='realestate_directory.states'),
        ),
    ]
