# Generated by Django 4.2.17 on 2025-10-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communication', '0010_clientcontact_address_clientcontact_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledemail',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduledemail',
            name='failed_emails',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scheduledemail',
            name='success_emails',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='scheduledemail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
