# Generated by Django 4.2.17 on 2026-01-23 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Assistance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='user',
        ),
        migrations.AddField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='Chat with SurplusIndex', max_length=255),
        ),
        migrations.AddField(
            model_name='messages',
            name='attachment',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Assistance.conversation'),
        ),
        migrations.AddField(
            model_name='messages',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messages',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messages',
            name='sender_type',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('system', 'System')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
