# Generated by Django 4.2.17 on 2025-08-16 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AllSettings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientsettings',
            old_name='manage_sub_hidden',
            new_name='manage_sub_show_hidden',
        ),
    ]
