# Generated by Django 4.2.17 on 2025-09-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllSettings', '0002_rename_manage_sub_hidden_clientsettings_manage_sub_show_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsettings',
            name='alldata_show_filter',
            field=models.BooleanField(default=True),
        ),
    ]
