# Generated by Django 4.2.17 on 2025-09-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllSettings', '0003_clientsettings_alldata_show_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsettings',
            name='purchased_show_filter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='purchased_show_prospecting_filter',
            field=models.BooleanField(default=True),
        ),
    ]
