# Generated by Django 4.2.17 on 2026-02-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllSettings', '0004_clientsettings_purchased_show_filter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('changed_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('state', models.CharField(max_length=100)),
                ('tax', models.BooleanField(default=False)),
                ('mortgage', models.BooleanField(default=False)),
                ('preforeclosure', models.BooleanField(default=False)),
                ('postforeclosure', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
