# Generated by Django 4.2.17 on 2025-04-10 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateField(blank=True, null=True)),
                ('order_detail', models.CharField(blank=True, max_length=255)),
                ('order_status', models.CharField(blank=True, choices=[('running', 'Running'), ('completed', 'Completed')], max_length=100)),
                ('payment_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('requested', 'Requested'), ('paid', 'Paid'), ('not_paid', 'Not Paid')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_status', models.CharField(blank=True, choices=[('assigned', 'Assigned'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('revision', 'Revision')], max_length=100, null=True)),
                ('delivery_note', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_Client.orders')),
            ],
        ),
    ]
