# Generated by Django 4.2.17 on 2025-04-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Client', '0002_remove_deliveries_order_orders_deliveries'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
