# Generated by Django 4.2.17 on 2025-04-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Client', '0004_deliveries_delivred_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='delivred_in',
            new_name='delivered_in',
        ),
    ]
