# Generated by Django 4.2.17 on 2025-04-15 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0019_alter_userpayment_stripe_checkout_id'),
        ('Admin_Client', '0005_rename_delivred_in_deliveries_delivered_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='si_user.userpayment'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('requested', 'Requested'), ('in_escrow', 'In Escrow'), ('paid', 'Paid'), ('not_paid', 'Not Paid')], max_length=100),
        ),
    ]
