# Generated by Django 4.2.17 on 2025-08-15 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0034_transactions'),
        ('Admin_Client', '0006_orders_transaction_alter_orders_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='si_user.transactions'),
        ),
    ]
