# Generated by Django 4.2.17 on 2025-01-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='court_record',
            name='county',
            field=models.CharField(blank=True, max_length=100, verbose_name='County'),
        ),
        migrations.AddField(
            model_name='court_record',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='State'),
        ),
    ]
