# Generated by Django 4.2.17 on 2025-01-19 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0002_court_record_county_court_record_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='foreclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(max_length=225)),
                ('county', models.CharField(max_length=225)),
                ('sale_date', models.DateField()),
                ('sale_type', models.CharField(max_length=225)),
                ('sale_status', models.CharField(max_length=225)),
                ('fcl_final_judgment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('possible_surplus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('verified_surplus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('court_record_id', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='court_record_id_for_foreclosure', to='propertydata.court_record', verbose_name='Case id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
