# Generated by Django 4.2.17 on 2025-01-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0003_foreclosure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreclosure',
            name='sale_date',
            field=models.DateField(blank=True),
        ),
    ]
