# Generated by Django 4.2.17 on 2025-01-21 04:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('propertydata', '0005_foreclosure_archived_by_foreclosure_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_status', models.CharField(blank=True, default='Need to Call', max_length=255)),
                ('call_comment', models.TextField(blank=True, max_length=500)),
                ('agreement_status', models.CharField(blank=True, choices=[('not signed', 'Not Signed'), ('agreement mailed', 'Agreement Mailed'), ('agreement signed', 'Agreement Signed')], default='Not Signed', max_length=255)),
                ('agreement_comment', models.TextField(blank=True, max_length=500)),
                ('claim_status', models.CharField(blank=True, choices=[('not signed', 'Not Signed'), ('preparing documents', 'Preparing Documents'), ('claim submitted', 'Claim Submitted'), ('waiting for courts decision', 'Waiting for Courts Decision'), ('fund disbursed', 'Fund Disbursed')], default='Not Signed', max_length=255)),
                ('claim_comment', models.TextField(blank=True, max_length=500)),
                ('client', models.ManyToManyField(blank=True, related_name='user_as_client', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ManyToManyField(blank=True, related_name='status_for_lead', to='propertydata.foreclosure')),
            ],
        ),
    ]
