# Generated by Django 4.2.17 on 2025-01-27 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('propertydata', '0006_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='archived_by',
            field=models.ManyToManyField(blank=True, related_name='user_who_archived', to=settings.AUTH_USER_MODEL),
        ),
    ]
