# Generated by Django 4.2.17 on 2025-01-28 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('propertydata', '0007_status_archived_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='client',
        ),
        migrations.RemoveField(
            model_name='status',
            name='lead',
        ),
        migrations.AddField(
            model_name='status',
            name='client',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_as_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='status',
            name='lead',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='foreclosure_as_lead', to='propertydata.foreclosure'),
        ),
    ]
