# Generated by Django 4.2.17 on 2025-01-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0008_remove_status_client_remove_status_lead_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='archived_by',
        ),
        migrations.AddField(
            model_name='status',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
