# Generated by Django 4.2.17 on 2025-02-16 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('propertydata', '0009_remove_status_archived_by_status_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreclosure',
            name='case_search_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foreclosure',
            name='case_search_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='foreclosure',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
