# Generated by Django 4.2.17 on 2025-02-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0010_foreclosure_case_search_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreclosure',
            name='surplus_status',
            field=models.CharField(choices=[('not determined', 'Not Determined'), ('possible surplus', 'Possible Surplus'), ('fund available', 'Fund Available'), ('motion filed', 'Motion Filed'), ('fund claimed', 'Fund Claimed'), ('no surplus', 'No Surplus')], default='Not Determined', max_length=100),
        ),
    ]
