# Generated by Django 4.2.17 on 2025-02-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0012_remove_foreclosure_court_record_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='related_contacts',
            field=models.ManyToManyField(blank=True, to='propertydata.contact'),
        ),
    ]
