# Generated by Django 4.2.17 on 2025-02-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0013_contact_related_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Designation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Designation'),
        ),
        migrations.AddField(
            model_name='contact',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Business Name'),
        ),
        migrations.CreateModel(
            name='ForeclosingEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_name', models.CharField(blank=True, max_length=255)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('dba', models.ManyToManyField(blank=True, to='propertydata.foreclosingentity')),
            ],
        ),
        migrations.AlterField(
            model_name='foreclosure',
            name='plaintiff',
            field=models.ManyToManyField(blank=True, default='', related_name='plaintiff_for_foreclosure', to='propertydata.foreclosingentity', verbose_name='Plaintiff'),
        ),
    ]
