# Generated by Django 4.2.17 on 2025-02-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0014_contact_designation_contact_business_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreclosure',
            name='sale_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foreclosure',
            name='sale_status',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='foreclosure',
            name='sale_type',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
