# Generated by Django 4.2.17 on 2025-02-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0015_alter_foreclosure_sale_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreclosure',
            name='case_number_ext',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Case Extension'),
        ),
    ]
