# Generated by Django 4.2.17 on 2025-02-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0016_alter_foreclosure_case_number_ext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreclosure',
            name='fcl_final_judgment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='foreclosure',
            name='possible_surplus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='foreclosure',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='foreclosure',
            name='surplus_status',
            field=models.CharField(blank=True, choices=[('not determined', 'Not Determined'), ('possible surplus', 'Possible Surplus'), ('fund available', 'Fund Available'), ('motion filed', 'Motion Filed'), ('fund claimed', 'Fund Claimed'), ('no surplus', 'No Surplus')], default='Not Determined', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foreclosure',
            name='verified_surplus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
