# Generated by Django 4.2.17 on 2025-03-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0017_alter_foreclosure_fcl_final_judgment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foreclosure',
            options={'verbose_name': 'Foreclosure', 'verbose_name_plural': 'Foreclosures'},
        ),
        migrations.RemoveField(
            model_name='foreclosingentity',
            name='dba',
        ),
        migrations.AddField(
            model_name='foreclosingentity',
            name='dba',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
