# Generated by Django 4.2.17 on 2025-03-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0018_alter_foreclosure_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Designation',
            new_name='designation',
        ),
    ]
