# Generated by Django 4.2.17 on 2025-03-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0019_rename_designation_contact_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreclosure',
            name='case_search_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='foreclosure',
            name='sale_status',
            field=models.CharField(blank=True, choices=[('pending', 'Active'), ('completed', 'Sold'), ('cancelled', 'Cancelled')], max_length=225, null=True),
        ),
    ]
