# Generated by Django 4.2.17 on 2025-03-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0020_alter_foreclosure_case_search_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreclosure',
            name='case_search_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('verified', 'Verified')], max_length=100),
        ),
    ]
