# Generated by Django 4.2.17 on 2025-03-15 23:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('propertydata', '0021_alter_foreclosure_case_search_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='skp_assignedto',
            field=models.ManyToManyField(blank=True, null=True, related_name='assign_skp', to=settings.AUTH_USER_MODEL),
        ),
    ]
