# Generated by Django 4.2.17 on 2025-03-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0022_contact_skp_assignedto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreclosure',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('tax', 'Tax'), ('mortgage', 'Mortgage'), ('others', 'Others')], max_length=225, null=True),
        ),
    ]
