# Generated by Django 4.2.17 on 2025-03-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0023_alter_foreclosure_sale_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreclosure',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('tax', 'Tax'), ('mortgage', 'Mortgage')], max_length=225, null=True),
        ),
    ]
