# Generated by Django 4.2.17 on 2025-03-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0024_alter_foreclosure_sale_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='number_in_use',
            field=models.IntegerField(blank=True, max_length=14, null=True),
        ),
    ]
