# Generated by Django 4.2.17 on 2025-03-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0025_status_number_in_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='number_in_use',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
