# Generated by Django 4.2.17 on 2025-03-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0026_alter_status_number_in_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='call_negotiate_comment',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='status',
            name='call_negotiate_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='status',
            name='find_contact_comment',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='status',
            name='find_contact_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='status',
            name='follow_up_comment',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='status',
            name='follow_up_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='status',
            name='fund_collection_comment',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='status',
            name='fund_collection_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='status',
            name='fund_confirm_comment',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='status',
            name='fund_confirm_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='status',
            name='paperwork_comment',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='status',
            name='paperwork_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='status',
            name='submit_paperwork_comment',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='status',
            name='submit_paperwork_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='status',
            name='waiting_comment',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='status',
            name='waiting_status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
