# Generated by Django 4.2.17 on 2025-03-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0027_status_call_negotiate_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreclosure',
            name='surplus_status',
            field=models.CharField(blank=True, choices=[('not determined', 'Not Determined'), ('possible surplus', 'Possible Surplus'), ('no possible surplus', 'No Possible Surplus'), ('fund available', 'Fund Available'), ('motion filed', 'Motion Filed'), ('fund claimed', 'Fund Claimed'), ('no surplus', 'No Surplus')], default='Not Determined', max_length=100, null=True),
        ),
    ]
