# Generated by Django 4.2.17 on 2025-04-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0029_remove_contact_skp_assignedto_contact_skp_assignedto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='skiptrace_comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
