# Generated by Django 4.2.17 on 2025-04-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0030_contact_skiptrace_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreclosure',
            name='case_search_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
