# Generated by Django 4.2.17 on 2025-04-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0031_foreclosure_case_search_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foreclosure',
            name='changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
