# Generated by Django 4.2.17 on 2025-04-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0032_alter_contact_changed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='first_contact_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='first_contact_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='first_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='first_contact_phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='second_contact_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='second_contact_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='second_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='second_contact_phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
