# Generated by Django 4.2.17 on 2025-04-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0034_rename_find_contact_comment_status_find_contact_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='find_contact_notes',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
