# Generated by Django 4.2.17 on 2025-04-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0035_alter_status_find_contact_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='find_contact_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
