# Generated by Django 4.2.17 on 2025-04-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0036_alter_status_find_contact_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='number_in_use',
        ),
        migrations.AlterField(
            model_name='status',
            name='find_contact_status',
            field=models.CharField(blank=True, choices=[('not_assigned', 'Not Assigned'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('verified', 'Verified')], max_length=255),
        ),
    ]
