# Generated by Django 4.2.17 on 2025-04-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0037_remove_status_number_in_use_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='find_contact_status',
            field=models.CharField(blank=True, choices=[('not_assigned', 'Not Assigned'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('verified', 'Verified')], default='Not Assigned', max_length=255),
        ),
    ]
