# Generated by Django 4.2.17 on 2025-04-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0038_alter_status_find_contact_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='call_negotiate_status',
            field=models.CharField(blank=True, choices=[('not_assigned', 'Not Assigned'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('verified', 'Verified')], max_length=255),
        ),
    ]
