# Generated by Django 4.2.17 on 2025-05-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0040_alter_foreclosure_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='call_status',
            field=models.CharField(blank=True, choices=[('need_to_call', 'Need to Call'), ('responded', 'Responded'), ('not_responded', 'Not Responded'), ('re_skiptrace', 'Re Skiptrace')], default='Need to Call', max_length=255),
        ),
    ]
