# Generated by Django 4.2.17 on 2025-05-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0041_alter_status_call_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='negotiation_status',
            field=models.CharField(blank=True, choices=[('interested', 'Interested'), ('not_interested', 'Not Interested'), ('not_sure', 'Not Sure')], max_length=255),
        ),
        migrations.AlterField(
            model_name='status',
            name='call_status',
            field=models.CharField(blank=True, choices=[('need_to_call', 'Need to Call'), ('responded', 'Responded'), ('not_responded', 'Not Responded'), ('re_skiptrace', 'Re Skiptrace')], default='NEED_TO_CALL', max_length=255),
        ),
    ]
