# Generated by Django 4.2.17 on 2025-06-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0042_status_negotiation_status_alter_status_call_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='agreement_status',
        ),
        migrations.AddField(
            model_name='status',
            name='closing_status',
            field=models.CharField(blank=True, choices=[('preparing_documents', 'Preparing Documents'), ('agreement_sent', 'Agreement Sent'), ('agreement_signed', 'Agreement Signed'), ('conversion_in_progress', 'Conversion In Progress'), ('closed_funded', 'Closed Funded'), ('closed_not_funded', 'Closed Not Funded')], max_length=255),
        ),
        migrations.AlterField(
            model_name='status',
            name='claim_status',
            field=models.CharField(blank=True, default='Not Signed', max_length=255),
        ),
    ]
