# Generated by Django 4.2.17 on 2025-06-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0043_remove_status_agreement_status_status_closing_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='skiptracing_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('skiptraced_found', 'Skiptraced Found'), ('skiptraced_not_found', 'Skiptraced Not Found'), ('cold_calling_located', 'Cold Calling Located'), ('cold_calling_not_located', 'Cold Calling Not Located')], default='pending', max_length=255),
        ),
    ]
