# Generated by Django 4.2.17 on 2025-06-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0044_status_skiptracing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='agreement_comment',
        ),
        migrations.RemoveField(
            model_name='status',
            name='call_comment',
        ),
        migrations.RemoveField(
            model_name='status',
            name='call_negotiate_comment',
        ),
        migrations.RemoveField(
            model_name='status',
            name='call_negotiate_status',
        ),
        migrations.RemoveField(
            model_name='status',
            name='claim_comment',
        ),
        migrations.RemoveField(
            model_name='status',
            name='claim_status',
        ),
        migrations.RemoveField(
            model_name='status',
            name='follow_up_comment',
        ),
        migrations.RemoveField(
            model_name='status',
            name='follow_up_status',
        ),
        migrations.RemoveField(
            model_name='status',
            name='fund_collection_comment',
        ),
        migrations.RemoveField(
            model_name='status',
            name='fund_collection_status',
        ),
        migrations.RemoveField(
            model_name='status',
            name='fund_confirm_comment',
        ),
        migrations.RemoveField(
            model_name='status',
            name='fund_confirm_status',
        ),
        migrations.RemoveField(
            model_name='status',
            name='paperwork_comment',
        ),
        migrations.RemoveField(
            model_name='status',
            name='paperwork_status',
        ),
        migrations.RemoveField(
            model_name='status',
            name='submit_paperwork_comment',
        ),
        migrations.RemoveField(
            model_name='status',
            name='submit_paperwork_status',
        ),
        migrations.RemoveField(
            model_name='status',
            name='waiting_comment',
        ),
        migrations.RemoveField(
            model_name='status',
            name='waiting_status',
        ),
        migrations.AlterField(
            model_name='status',
            name='skiptracing_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('skiptraced_found', 'Skiptraced Found'), ('skiptraced_not_found', 'Skiptraced Not Found'), ('cold_calling_located', 'Cold Calling Located'), ('cold_calling_not_located', 'Cold Calling Not Located')], default='Pending', max_length=255),
        ),
    ]
