# Generated by Django 4.2.17 on 2025-06-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0045_remove_status_agreement_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='doc_status',
            field=models.CharField(blank=True, choices=[('not_started', 'not_started'), ('started', 'started'), ('prepared', 'prepared'), ('mailed', 'mailed')], max_length=255),
        ),
    ]
