# Generated by Django 4.2.17 on 2025-06-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0046_status_doc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='doc_status',
            field=models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('started', 'Started'), ('prepared', 'Prepared'), ('mailed', 'Mailed')], max_length=255),
        ),
    ]
