# Generated by Django 4.2.17 on 2025-06-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0048_status_ag_sent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='lp_status',
            field=models.CharField(blank=True, choices=[('attorney_submit', 'Attorney Submit'), ('direct_submit', 'Direct Submit'), ('motion_filed', 'Motion Filed'), ('motion_granted', 'Motion Granted'), ('motion_denied', 'Motion Denied')], max_length=255),
        ),
        migrations.AlterField(
            model_name='status',
            name='ag_sent_status',
            field=models.CharField(blank=True, choices=[('not_delivered', 'Not Delivered'), ('delivered', 'Delivered'), ('returned_signed', 'Returned Signed'), ('returned_not_signed', 'Returned Not Signed')], max_length=255),
        ),
        migrations.AlterField(
            model_name='status',
            name='closing_status',
            field=models.CharField(blank=True, choices=[('preparing_documents', 'Preparing Documents'), ('agreement_sent', 'Agreement Sent'), ('conversion_in_progress', 'Conversion In Progress'), ('closed_funded', 'Closed Funded'), ('closed_not_funded', 'Closed Not Funded')], max_length=255),
        ),
    ]
