# Generated by Django 4.2.17 on 2025-06-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0049_status_lp_status_alter_status_ag_sent_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='attorney_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='status',
            name='fee_agreement_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='status',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='status',
            name='other_costs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='status',
            name='total_disbursed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
