# Generated by Django 4.2.17 on 2025-06-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0050_status_attorney_cost_status_fee_agreement_share_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='call_status',
            field=models.CharField(blank=True, choices=[('Need to Call', 'Need to Call'), ('Responded', 'Responded'), ('Not Responded', 'Not Responded'), ('Re Skiptrace', 'Re Skiptrace')], default='NEED_TO_CALL', max_length=255),
        ),
        migrations.AlterField(
            model_name='status',
            name='lp_status',
            field=models.CharField(blank=True, choices=[('attorney_submit', 'Attorney Submit'), ('direct_submit', 'Direct Submit'), ('motion_granted', 'Motion Granted'), ('motion_denied', 'Motion Denied')], max_length=255),
        ),
    ]
