# Generated by Django 4.2.17 on 2025-09-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0052_alter_status_call_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreclosure',
            name='sale_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('sold', 'Sold'), ('cancelled', 'Cancelled')], max_length=225, null=True),
        ),
    ]
