# Generated by Django 4.2.17 on 2025-09-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0053_alter_foreclosure_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreclosure',
            name='sale_status',
            field=models.CharField(blank=True, choices=[('pending', 'Active'), ('sold', 'Sold'), ('cancelled', 'Cancelled')], max_length=225, null=True),
        ),
    ]
