# Generated by Django 4.2.17 on 2025-09-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0054_alter_foreclosure_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreclosure',
            name='sale_status',
            field=models.CharField(blank=True, choices=[('pending', 'Active'), ('sold', 'Sold'), ('cancelled', 'Cancelled'), ('sold_to_plaintiff', 'Sold To Plaintiff')], max_length=225, null=True),
        ),
    ]
