# Generated by Django 4.2.17 on 2025-10-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0055_alter_foreclosure_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreclosure',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
