# Generated by Django 4.2.17 on 2025-11-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0057_alter_foreclosure_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreclosure',
            name='case_number_ext',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Case Extension'),
        ),
    ]
