# Generated by Django 4.2.17 on 2025-11-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0058_alter_foreclosure_case_number_ext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreclosure',
            name='sale_status',
            field=models.CharField(blank=True, choices=[('pending', 'Active'), ('sold', 'Sold'), ('unsold', 'Unsold'), ('cancelled', 'Cancelled'), ('sold_to_plaintiff', 'Sold To Plaintiff'), ('bankruptcy_hold', 'Bankruptcy Hold')], max_length=225, null=True),
        ),
    ]
