# Generated by Django 4.2.17 on 2025-12-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0059_alter_foreclosure_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreclosure',
            name='case_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Case Number'),
        ),
        migrations.AlterField(
            model_name='foreclosure',
            name='case_number_ext',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Case Extension'),
        ),
        migrations.AlterField(
            model_name='foreclosure',
            name='case_search_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('verified', 'Verified')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foreclosure',
            name='case_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Case Status'),
        ),
        migrations.AlterField(
            model_name='foreclosure',
            name='case_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Case Type'),
        ),
        migrations.AlterField(
            model_name='foreclosure',
            name='comment',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='foreclosure',
            name='county',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='foreclosure',
            name='court_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Court Name'),
        ),
        migrations.AlterField(
            model_name='foreclosure',
            name='state',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
