# Generated by Django 4.2.17 on 2025-12-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0060_alter_foreclosure_case_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreclosure',
            name='case_number_ext',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Case Extension'),
        ),
        migrations.AlterField(
            model_name='foreclosure',
            name='case_status',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Case Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foreclosure',
            name='case_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Case Type'),
        ),
        migrations.AlterField(
            model_name='foreclosure',
            name='court_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Court Name'),
        ),
    ]
