# Generated by Django 4.2.17 on 2025-12-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0061_alter_foreclosure_case_number_ext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreclosure',
            name='appraised_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='foreclosure',
            name='auction_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
