# Generated by Django 4.2.17 on 2025-12-30 06:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0062_foreclosure_appraised_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
