# Generated by Django 4.2.17 on 2026-01-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0063_status_changed_at_status_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreclosure',
            name='sale_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('sold', 'Sold'), ('unsold', 'Unsold'), ('cancelled', 'Cancelled'), ('sold to plaintiff', 'Sold To Plaintiff'), ('bankruptcy hold', 'Bankruptcy Hold')], max_length=225, null=True),
        ),
    ]
