# Generated by Django 4.2.17 on 2025-02-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foreclosure_Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=255)),
                ('county', models.CharField(blank=True, max_length=255)),
                ('population', models.IntegerField(blank=True)),
                ('recorder', models.URLField(blank=True)),
                ('assessor', models.URLField(blank=True)),
                ('tax_collector', models.URLField(blank=True)),
                ('gis', models.URLField(blank=True)),
                ('district', models.URLField(blank=True)),
                ('civil', models.URLField(blank=True)),
                ('municipal', models.URLField(blank=True)),
                ('probate', models.URLField(blank=True)),
                ('superior', models.URLField(blank=True)),
                ('supreme', models.URLField(blank=True)),
                ('surrogate', models.URLField(blank=True)),
                ('excess_funds_list', models.URLField(blank=True)),
                ('efl_updated_from', models.DateField(blank=True, null=True)),
                ('efl_updated_to', models.DateField(blank=True, null=True)),
                ('tax_sale', models.URLField(blank=True)),
                ('tax_sale_data_status', models.CharField(blank=True, max_length=255)),
                ('tax_sale_case_search', models.URLField(blank=True)),
                ('tax_sale_next', models.DateField(blank=True, null=True)),
                ('tax_sale_updated_from', models.DateField(blank=True, null=True)),
                ('tax_sale_updated_to', models.DateField(blank=True, null=True)),
                ('mortgage_sale', models.URLField(blank=True)),
                ('mortgage_sale_data_status', models.CharField(blank=True, max_length=255)),
                ('mortgage_sale_case_search', models.URLField(blank=True)),
                ('mortgage_sale_next', models.DateField(blank=True, null=True)),
                ('mortgage_sale_updated_from', models.DateField(blank=True, null=True)),
                ('mortgage_sale_updated_to', models.DateField(blank=True, null=True)),
                ('public_notice', models.URLField(blank=True)),
            ],
        ),
    ]
