# Generated by Django 4.2.17 on 2025-02-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='directoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=255)),
                ('county', models.CharField(blank=True, max_length=255)),
                ('recorder', models.URLField(blank=True)),
                ('assessor', models.URLField(blank=True)),
                ('tax_collector', models.URLField(blank=True)),
                ('gis', models.URLField(blank=True)),
                ('district', models.URLField(blank=True)),
                ('civil', models.URLField(blank=True)),
                ('municipal', models.URLField(blank=True)),
                ('probate', models.URLField(blank=True)),
                ('superior', models.URLField(blank=True)),
                ('supreme', models.URLField(blank=True)),
                ('surrogate', models.URLField(blank=True)),
                ('public_notice', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='foreclosure_events',
            name='assessor',
        ),
        migrations.RemoveField(
            model_name='foreclosure_events',
            name='civil',
        ),
        migrations.RemoveField(
            model_name='foreclosure_events',
            name='district',
        ),
        migrations.RemoveField(
            model_name='foreclosure_events',
            name='efl_updated_from',
        ),
        migrations.RemoveField(
            model_name='foreclosure_events',
            name='efl_updated_to',
        ),
        migrations.RemoveField(
            model_name='foreclosure_events',
            name='excess_funds_list',
        ),
        migrations.RemoveField(
            model_name='foreclosure_events',
            name='gis',
        ),
        migrations.RemoveField(
            model_name='foreclosure_events',
            name='mortgage_sale',
        ),
        migrations.RemoveField(
            model_name='foreclosure_events',
            name='mortgage_sale_case_search',
        ),
        migrations.RemoveField(
            model_name='foreclosure_events',
            name='mortgage_sale_data_status',
        ),
        migrations.RemoveField(
            model_name='foreclosure_events',
            name='mortgage_sale_next',
        ),
        migrations.RemoveField(
            model_name='foreclosure_events',
            name='mortgage_sale_updated_from',
        ),
        migrations.RemoveField(
            model_name='foreclosure_events',
            name='mortgage_sale_updated_to',
        ),
        migrations.RemoveField(
            model_name='foreclosure_events',
            name='municipal',
        ),
        migrations.RemoveField(
            model_name='foreclosure_events',
            name='probate',
        ),
        migrations.RemoveField(
            model_name='foreclosure_events',
            name='public_notice',
        ),
        migrations.RemoveField(
            model_name='foreclosure_events',
            name='recorder',
        ),
        migrations.RemoveField(
            model_name='foreclosure_events',
            name='superior',
        ),
        migrations.RemoveField(
            model_name='foreclosure_events',
            name='supreme',
        ),
        migrations.RemoveField(
            model_name='foreclosure_events',
            name='surrogate',
        ),
        migrations.RemoveField(
            model_name='foreclosure_events',
            name='tax_collector',
        ),
        migrations.RemoveField(
            model_name='foreclosure_events',
            name='tax_sale',
        ),
        migrations.RemoveField(
            model_name='foreclosure_events',
            name='tax_sale_case_search',
        ),
        migrations.RemoveField(
            model_name='foreclosure_events',
            name='tax_sale_data_status',
        ),
        migrations.RemoveField(
            model_name='foreclosure_events',
            name='tax_sale_next',
        ),
        migrations.RemoveField(
            model_name='foreclosure_events',
            name='tax_sale_updated_from',
        ),
        migrations.RemoveField(
            model_name='foreclosure_events',
            name='tax_sale_updated_to',
        ),
        migrations.AddField(
            model_name='foreclosure_events',
            name='event_case_search',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='foreclosure_events',
            name='event_next',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foreclosure_events',
            name='event_site',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='foreclosure_events',
            name='event_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='foreclosure_events',
            name='event_updated_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foreclosure_events',
            name='event_updated_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foreclosure_events',
            name='sale_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
