# Generated by Django 4.2.17 on 2025-02-15 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realestate_directory', '0002_directorydata_remove_foreclosure_events_assessor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreclosure_events',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foreclosure_events',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realestate_directory.directorydata'),
        ),
    ]
