# Generated by Django 4.2.17 on 2025-09-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_directory', '0003_foreclosure_events_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreclosure_events',
            name='post_event_next',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foreclosure_events',
            name='post_event_updated_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foreclosure_events',
            name='post_event_updated_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
