# Generated by Django 4.2.17 on 2025-09-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_directory', '0004_foreclosure_events_post_event_next_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreclosure_events',
            name='assessor',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='foreclosure_events',
            name='civil',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='foreclosure_events',
            name='district',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='foreclosure_events',
            name='gis',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='foreclosure_events',
            name='municipal',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='foreclosure_events',
            name='probate',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='foreclosure_events',
            name='public_notice',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='foreclosure_events',
            name='recorder',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='foreclosure_events',
            name='superior',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='foreclosure_events',
            name='supreme',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='foreclosure_events',
            name='surrogate',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='foreclosure_events',
            name='tax_collector',
            field=models.URLField(blank=True),
        ),
    ]
