# Generated by Django 4.2.17 on 2025-09-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_directory', '0005_foreclosure_events_assessor_foreclosure_events_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreclosure_events',
            name='event_case_search',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foreclosure_events',
            name='event_site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foreclosure_events',
            name='event_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foreclosure_events',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
