# Generated by Django 4.2.17 on 2025-09-14 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_directory', '0006_alter_foreclosure_events_event_case_search_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foreclosure_events',
            unique_together={('state', 'county', 'sale_type')},
        ),
    ]
