# Generated by Django 4.2.17 on 2025-09-14 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_directory', '0007_alter_foreclosure_events_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foreclosure_events',
            unique_together=set(),
        ),
    ]
