# Generated by Django 4.2.17 on 2025-09-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_directory', '0008_alter_foreclosure_events_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=2)),
            ],
        ),
    ]
