# Generated by Django 4.2.17 on 2026-01-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_directory', '0009_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreclosure_events',
            name='business_search',
            field=models.URLField(blank=True),
        ),
    ]
