# Generated by Django 4.2.17 on 2026-01-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SheriffAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('sale_date', models.DateField()),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('case_status', models.CharField(max_length=50)),
                ('parcel', models.CharField(blank=True, max_length=50, null=True)),
                ('property_address', models.TextField()),
                ('fcl_final_judgment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('appraised_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('opening_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sold_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sold_to', models.CharField(blank=True, max_length=100, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
