# Generated by Django 4.2.17 on 2026-02-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('price_id', models.CharField(blank=True, max_length=255, null=True)),
                ('price_amount', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('tax', models.BooleanField(default=False)),
                ('mortgage', models.BooleanField(default=False)),
                ('preforeclosure', models.BooleanField(default=False)),
                ('postforeclosure', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SheriffAuction',
        ),
    ]
