# Generated by Django 4.2.17 on 2026-02-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0002_automation_delete_sheriffauction'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='update_interval',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
