# Generated by Django 4.2.17 on 2026-02-18 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('si_user', '0042_userdetail_payment_method'),
        ('Automation', '0003_automation_update_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automation',
            name='state',
        ),
        migrations.AddField(
            model_name='automation',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='automation',
            name='expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automation',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=50),
        ),
        migrations.AddField(
            model_name='automation',
            name='states',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='automation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('closed', 'Closed')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='automation',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='si_user.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='automation',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='si_user.usertransactions'),
        ),
    ]
