# Generated by Django 4.2.17 on 2026-02-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0004_remove_automation_state_automation_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='surplus_capped',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
