# Generated by Django 4.2.17 on 2026-02-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0005_automation_surplus_capped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('failed', 'Failed')], default='unpaid', max_length=50),
        ),
    ]
