# Generated by Django 4.2.17 on 2026-02-21 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0042_userdetail_payment_method'),
        ('Automation', '0006_alter_automation_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='si_user.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='automation',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='si_user.usertransactions'),
        ),
    ]
