# Generated by Django 4.2.17 on 2026-02-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0007_alter_automation_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='surplus_capped',
            field=models.DecimalField(blank=True, decimal_places=2, default=15000, max_digits=15, null=True),
        ),
    ]
