# Generated by Django 4.2.17 on 2026-02-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0008_alter_automation_surplus_capped'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='enrolled_stripe_subscrption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
