# Generated by Django 4.2.17 on 2026-02-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0046_stripesubscription_plan'),
        ('Automation', '0009_automation_enrolled_stripe_subscrption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automation',
            name='transaction',
        ),
        migrations.AddField(
            model_name='automation',
            name='transaction',
            field=models.ManyToManyField(blank=True, null=True, to='si_user.usertransactions'),
        ),
    ]
