# Generated by Django 4.2.17 on 2026-02-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0010_remove_automation_transaction_automation_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='automation',
            name='renew_when_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automation',
            name='renew_when_limit',
            field=models.BooleanField(default=False),
        ),
    ]
