# Generated by Django 4.2.17 on 2026-03-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si_user', '0046_stripesubscription_plan'),
        ('Automation', '0011_automation_auto_renew_automation_renew_when_expired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='transaction',
            field=models.ManyToManyField(to='si_user.usertransactions'),
        ),
    ]
