# Generated by Django 4.2.17 on 2026-03-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0064_alter_foreclosure_sale_status'),
        ('Automation', '0012_alter_automation_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='post_f_to_deliver',
            field=models.ManyToManyField(related_name='post_to_deliver', to='propertydata.foreclosure'),
        ),
        migrations.AddField(
            model_name='automation',
            name='pre_f_to_deliver',
            field=models.ManyToManyField(related_name='pre_to_deliver', to='propertydata.foreclosure'),
        ),
        migrations.AddField(
            model_name='automation',
            name='verified_s_to_deliver',
            field=models.ManyToManyField(related_name='verified_to_deliver', to='propertydata.foreclosure'),
        ),
    ]
