# Generated by Django 4.2.17 on 2026-03-10 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0064_alter_foreclosure_sale_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Automation', '0013_automation_post_f_to_deliver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationDeliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('automation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Automation.automation')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('data', models.ManyToManyField(related_name='DataDelivered', to='propertydata.status')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
