# Generated by Django 4.2.17 on 2026-03-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0014_automationdeliveries'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationdeliveries',
            name='list_type',
            field=models.CharField(blank=True, choices=[('pre foreclosure', 'Pre Foreclosure'), ('post foreclosure', 'Post Foreclosure'), ('verified surplus', 'Verified Surplus')], max_length=100, null=True),
        ),
    ]
