# Generated by Django 4.2.17 on 2025-10-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propertydata', '0057_alter_foreclosure_sale_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportLeadFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('sale_type', models.CharField(blank=True, max_length=255, null=True)),
                ('sale_status', models.CharField(blank=True, max_length=255, null=True)),
                ('surplus_status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomExportOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='Default Template', max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('number_delivery', models.IntegerField()),
                ('delivery_type', models.CharField(choices=[('pre-foreclosure', 'Pre-Foreclosure'), ('post-foreclosure', 'Post-Foreclosure'), ('verified', 'Verified')], default='verified', max_length=20)),
                ('contact_align', models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], default='horizontal', max_length=20)),
                ('columns', models.JSONField(default=list, help_text='List of field names in desired order')),
                ('active', models.BooleanField(default=True)),
                ('filter_option', models.ManyToManyField(to='CustomDelivery.exportleadfilter')),
                ('old_leads', models.ManyToManyField(related_name='not_delivered', to='propertydata.foreclosure')),
                ('post_foreclosure', models.ManyToManyField(related_name='post_delivered', to='propertydata.foreclosure')),
                ('pre_foreclosure', models.ManyToManyField(related_name='pre_delivered', to='propertydata.foreclosure')),
                ('verified_surplus', models.ManyToManyField(related_name='verified_delivered', to='propertydata.foreclosure')),
            ],
        ),
    ]
