# Generated by Django 4.2.17 on 2025-10-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomDelivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customexportoptions',
            name='next_delivery_date',
            field=models.DateField(null=True),
        ),
    ]
