# Generated by Django 4.2.17 on 2025-11-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydata', '0057_alter_foreclosure_sale_status'),
        ('CustomDelivery', '0002_customexportoptions_next_delivery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDeliveryClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('contact_align', models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], default='horizontal', max_length=20)),
                ('columns', models.JSONField(default=list, help_text='List of field names in desired order')),
                ('old_leads', models.ManyToManyField(related_name='old_leads', to='propertydata.foreclosure')),
                ('post_foreclosure', models.ManyToManyField(related_name='postf_delivered', to='propertydata.foreclosure')),
                ('pre_foreclosure', models.ManyToManyField(related_name='pref_delivered', to='propertydata.foreclosure')),
                ('verified_surplus', models.ManyToManyField(related_name='vf_delivered', to='propertydata.foreclosure')),
            ],
        ),
    ]
