# Generated by Django 4.2.17 on 2025-11-01 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomDelivery', '0003_customdeliveryclients'),
    ]

    operations = [
        migrations.AddField(
            model_name='customexportoptions',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomDelivery.customdeliveryclients'),
        ),
    ]
