# Generated by Django 4.2.17 on 2025-11-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomDelivery', '0004_customexportoptions_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdeliveryclients',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
