# Generated by Django 4.2.17 on 2026-02-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomDelivery', '0005_customdeliveryclients_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customexportoptions',
            name='limit',
            field=models.IntegerField(default=100, help_text='Max leads per delivery'),
        ),
    ]
